name: Java CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        config:
          - { drill-admin-address: "https://complete-cat-correct.ngrok-free.app",
              drill-api-agent-id: "spring-realworld-backend-git-0",
              drill-group-id: "realworld-app-git-0"
          }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build JAR with Gradle
        run: ./gradlew clean build
      - name: Download Drill4J agent
        run: |
          curl -L -o /opt/file.zip https://github.com/Drill4J/java-agent/releases/download/v0.8.6-github-action.2/agent-linuxX64-0.8.6-github-action.2.zip
          unzip /opt/file.zip -d /opt
      - name: Run tests with drill agent
        run: |
          ./gradlew clean build
          java -agentpath:/opt/linuxX64-0.8.6-github-action.2/libdrill_agent.so=drillInstallationDir=/opt/linuxX64-0.8.6-github-action.2,adminAddress=${{matrix.config.drill-admin-address}},agentId=${{matrix.config.drill-api-agent-id}},groupId=${{matrix.config.drill-group-id}},apiKey=${{secrets.DRILL_API_KEY}},buildVersion=0.1.0,packagePrefixes=io/spring,vcsMetadataHash=${{github.event.pull_request.head.sha}},vcsMetadataParents=realworld-hash-0,vcsMetadataBranch=${{github.event.pull_request.head.ref}} -jar ./build/libs/spring-boot-realworld-example-app-0.0.1-SNAPSHOT.jar &
          APP_PID=$!
          sleep 120
          kill $APP_PID
      - name: Drill4J Github Action
        uses: Drill4J/drill-cicd-integration@feature/github-action-integration
        with:
          group-id: ${{ matrix.config.drill-group-id }}
          agent-id: ${{ matrix.config.drill-api-agent-id }}
          current-branch: ${{ github.event.pull_request.head.ref }}
          current-vcs-ref: ${{ github.event.pull_request.head.sha }}
          base-branch: ${{ github.event.pull_request.base.ref }}
          base-vcs-ref: ${{ github.event.pull_request.base.sha }}
          drill-address: ${{ matrix.config.drill-admin-address }}
          repo-token: ${{ secrets.TOKEN }}
          mode: "githubPullRequestReportByEvent"
